### ISSUE TITLE
duplicated (possibly overwritten) newsgroup message

### ISSUE THREAD

**Issue by De7vID** [zrajm/klingonska.org#7]
The first two postings to msn.onstage.startrek.expert.okrand on 1997-06-29 are identical:
https://github.com/zrajm/klingonska.org/blob/master/site/canon/1997-06-29a-news.txt
https://github.com/zrajm/klingonska.org/blob/master/site/canon/1997-06-29b-news.txt

**Comment by De7vID** [comment]
The description of the second message says it contains information about **qajatlh**, and since the posting is about that, it suggests the first message was accidentally overwritten.

**Comment by zrajm** [comment]
I tried to hunt down the missing post when this was first reported, but I was unsuccessful then.

Tried it again today, and I found that the data was actually in the repo, but hard to find. In the commit `42ed76` the file `canon/1997-06-29.txt` (which contained several different messages from Marc Okrand to the `msn.onstage.startrek.expert.okrand` newsgroup) was split into multiple files, one for each message. At that point I accidentally put in message number one twice, and forgot to include message number two.

I have now restored message number two (which is not about the Klingon language at all, but I kept it anyway, since the messages from MO to the `msn.onstage.startrek.expert.okrand` newsgroup does not seem to be archived anywhere else online.

So, the good news is that this issue is fixed. The bad news is that the restored message isn't very interested for someone who's looking for information about the Klingon languge.
